esaPythonPortfolio/charecters/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.display_charecters, name='display_charecters'),
    path('create_charecter/', views.create_charecter, name='create_charecter'),
    path('update_charecter/<str:pk>/',
         views.update_charecter, name='update_charecter'),
    path('delete_charecter/<str:pk>/',
         views.delete_charecter, name='delete_charecter'),
    path('charecter_success/', views.charecter_success, name='charecter_success'),
    path('team_success/', views.team_success, name='team_success'),
    path('display_teams/', views.display_teams, name='display_teams'),
    path('create_team/', views.create_team, name='create_team'),
    path('update_team/<str:pk>/',
         views.update_team, name='update_team'),
    path('delete_team/<str:pk>/',
         views.delete_team, name='delete_team'),
]
app_name = "charecters"

esaPythonPortfolio/dndDice/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]
app_name = "dndDice"

esaPythonPortfolio/esaPythonPortfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dndDice/', include('dndDice.urls', namespace="dndDice")),
    path('charecters/', include('charecters.urls', namespace="charecters"), name="charecters"),
    path('admin/', admin.site.urls),
]

esaPythonPortfolio/charecters/models.py
from django.db import models
from enum import IntEnum
# Create your models here.


class Charecter(models.Model):
    NEUTRAL = "neutral"
    LAWFUL = "lawful"
    CHAOTIC = "chaotic"

    GOOD = "good"
    EVIL = "evil"
    ALIGNEMENT_CHOICES = (
        (GOOD, "good"),
        (EVIL, "evil"),
    )
    ORIENTATION_CHOICES = (
        (NEUTRAL, "neutral"),
        (LAWFUL, "lawful"),
        (CHAOTIC, "chaotic"),
    )

    charecter_name = models.CharField(max_length=50)
    player_name = models.CharField(max_length=50)
    img_url = models.CharField(max_length=200)
    team = models.ForeignKey("Team",  on_delete=models.CASCADE, blank=False)
    class_type = models.CharField(
        verbose_name="class", max_length=50, blank=True)
    race = models.CharField(max_length=50, blank=True)
    hit_points = models.IntegerField(default=5)
    armor_class = models.IntegerField(default=5)
    orientation = models.CharField(
        max_length=10,
        choices=ORIENTATION_CHOICES, default=NEUTRAL)
    alignment = models.CharField(
        max_length=10,
        choices=ALIGNEMENT_CHOICES, default=GOOD)
    notes = models.TextField(blank=True, max_length=800)

    def __str__(self):
        return self.charecter_name


class Team(models.Model):
    team_name = models.CharField(max_length=50)
    notes = models.TextField(blank=True, max_length=800)

    def __str__(self):
        return self.team_name

esaPythonPortfolio/dndDice/models.py
from django.db import models

# Create your models here.

esaPythonPortfolio/charecters/forms.py
from django.forms import ModelForm
from .models import Charecter, Team


class CharecterForm(ModelForm):
    class Meta:
        model = Charecter
        fields = '__all__'


class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = '__all__'

esaPythonPortfolio/charecters/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Charecter, Team
from .forms import CharecterForm, TeamForm
from django.urls import reverse, resolve

# Create your views here.


def display_charecters(request):
    charecters = Charecter.objects.all()
    context = {'charecters': charecters}
    return render(request, 'charecters.html', context=context)


def create_charecter(request):
    form = CharecterForm()
    if request.method == 'POST':
        form = CharecterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('charecters:charecter_success')
    context = {'form': form}

    return render(request, 'create_charecter.html', context=context)


def update_charecter(request, pk):
    charecter = Charecter.objects.get(id=pk)
    form = CharecterForm(instance=charecter)

    if request.method == 'POST':
        form = CharecterForm(request.POST, instance=charecter)
        if form.is_valid():
            form.save()
            return redirect('charecters:charecter_success')
    context = {'form': form}
    return render(request, 'create_charecter.html', context=context)


def delete_charecter(request, pk):
    charecter = Charecter.objects.get(id=pk)
    if request.method == "POST":
        charecter.delete()
        return redirect('charecters:display_charecters')
    context = {'item': charecter}
    return render(request, 'delete_charecter.html', context=context)


def charecter_success(request):
    return render(request, 'charecter_success.html')


def team_success(request):
    return render(request, 'team_success.html')


def create_team(request):
    form = TeamForm()
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('charecters:team_success')
    context = {'form': form}
    return render(request, 'create_team.html', context=context)


def update_team(request, pk):
    team = Team.objects.get(id=pk)

    form = TeamForm(instance=team)

    if request.method == 'POST':
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            form.save()
            return redirect('charecters:team_success')
    context = {'form': form}
    return render(request, 'create_team.html', context=context)


def display_teams(request):

    teams = Team.objects.all()

    context = {'teams': teams}

    return render(request, 'teams.html', context=context)


def delete_team(request, pk):
    team = Team.objects.get(id=pk)
    print("team = ", team)
    if request.method == "POST":
        print("request.post = ", request.POST)
        team.delete()
        return redirect('charecters:display_teams')
    context = {'item': team}
    return render(request, 'delete_team.html', context=context)

esaPythonPortfolio/dndDice/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'dice.html')

esaPythonPortfolio/esaPythonPortfolio/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html', context={})

esaPythonPortfolio/charecters/templates/charecter_success.html
{% extends 'base.html' %} {% block title %}Charecter Created{% endblock title %}
{% block content %}
<div style="text-align: center; margin-top:15vw">
<h1>Charecter Creation Complete!</h1>
<a class="btn btn-sm btn-info" href="{% url 'charecters:display_charecters' %}"
  >Go back to charecter list</a
>
</div>
{% endblock %}

esaPythonPortfolio/charecters/templates/charecters.html
{% extends 'base.html' %} {% block content %}
<div style="font-family: fantasy;">
  <h1 style="margin:2vw; color:white; text-align: center;">Your Charecters:</h1>

  <div class="container">
    {% for char in charecters %}
    <div class="row" style="margin:.5vw">
      <div
        class="col"
        style="position: inherit; display: flex; flex-direction: column; "
      >
        <img
          style="border-style: ridge; width:25vw; height:20vw; margin:auto"
          src="{{ char.img_url }}"
        />
        <div
          style="margin:auto; background-color:white; border-style: ridge; width:25vw; "
        >
          <br />
          <h5>Charecter Name: {{ char.charecter_name }}</h5>

          <h5>Player Name: {{ char.player_name }}</h5>

          <h5>Team: {{ char.team }}</h5>
          <div style="text-align: center">
            <a
              class="btn btn-sm btn-info"
              href="{% url 'charecters:update_charecter' char.id%}"
              style="width: 12vw"
              >Update</a
            >
            <a
              class="btn btn-sm btn-danger"
              href="{% url 'charecters:delete_charecter' char.id %}"
              style="width: 12vw"
              >Delete</a
            >
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

esaPythonPortfolio/charecters/templates/create_charecter.html
{% extends 'base.html' %} {% block title %} Create Charecter{% endblock title %}
{% block content %}
<h1
  style="text-decoration: underline; color:white;margin-top:5vw; text-align: center"
>
  Create a Charecter
</h1>
<div style="background-color: lightgray; margin-top:5vw; padding:2vw">
  <h1 style="text-decoration: underline">Charecter</h1>
  <form
    action=""
    method="POST"
    style="display: flex; flex-direction:column; padding-bottom:2vw"
  >
    {% csrf_token %} {{form}}
    <input type="submit" name="submit" />
  </form>
</div>
{% endblock %}

esaPythonPortfolio/charecters/templates/create_team.html
{% extends 'base.html' %} {% block title %} Create Team{% endblock title %}
{%block content %}
<h1
  style="text-decoration: underline; color:white;margin-top:5vw; text-align: center"
>
  Create a Team
</h1>
<div style="background-color: lightgray; margin-top:5vw; padding:2vw">
  <h1 style="text-decoration: underline">Team</h1>
  <form action="" method="POST" style="display: flex; flex-direction:column">
    {% csrf_token %} {{form}}
    <input type="submit" name="submit" />
  </form>
</div>
{% endblock %}

esaPythonPortfolio/charecters/templates/delete_charecter.html
{% extends 'base.html' %} {% block title %}Delete Charecter{% endblock title %}
{% block content %}
<h1
  style="text-decoration: underline; color:white;margin-top:15vw; text-align: center"
>
  Are you sure you want to delete "{{item}}"?
</h1>
<form action="{% url 'charecters:delete_charecter' item.id %}" method="POST">
  {% csrf_token %}
  <div style="text-align: center">
    <a
      href="{% url 'charecters:display_charecters' %}"
      style="color: white; background-color: blue; width:2vw; padding:1vw; border-style:double"
      >Cancel</a
    >
    <input
      type="submit"
      name="Confirm"
      style="color: white; background-color: red; padding:1.2vw; "
    />
  </div>
</form>
{% endblock %}

esaPythonPortfolio/charecters/templates/delete_team.html
{% extends 'base.html' %} {% block title %}Delete Team{% endblock title %} 
{% block content %}
<h1
  style="text-decoration: underline; color:white;margin-top:15vw; text-align: center"
>
  Are you sure you want to delete "{{item}}"?
</h1>
<form action="{% url 'charecters:delete_team' item.id %}" method="POST">
  {% csrf_token %}
  <div style="text-align: center">
    <a
      href="{% url 'charecters:display_teams' %}"
      style="color: white; background-color: blue; width:2vw; padding:1vw; border-style:double"
      >Cancel</a
    >
    <input
      type="submit"
      name="Confirm"
      style="color: white; background-color: red; padding:1.2vw; "
    />
  </div>
</form>
{% endblock %}

esaPythonPortfolio/charecters/templates/success.html
{% extends 'base.html' %} {% block title %}Charecter Created{% endblock title %}
{% block content %}
<h1>Charecter Creation Complete!</h1>
<a class="btn btn-sm btn-info" href="{% url 'charecters:display_charecters' %}"
  >Go back to charecter list</a
>
{% endblock %}

esaPythonPortfolio/charecters/templates/team_success.html
{% extends 'base.html' %} {% block title %}Team Created{% endblock title %}
 {% block content %}
<div style="text-align: center; margin-top:15vw">
  <h1>Team Creation Complete!</h1>
  <a class="btn btn-sm btn-info" href="{% url 'charecters:display_teams' %}"
    >Go back to teams list</a
  >
</div>
{% endblock %}

esaPythonPortfolio/charecters/templates/teams.html
{% extends 'base.html' %}
{% block title %}Teams{% endblock title %}
{% block content %}
<div>
  <h1 style="margin:2vw; color:white; text-align: center;">Your Teams:</h1>
  {% for team in teams %}
  <div
    class="row"
    style="text-align: center; width: 50%; margin-left:25vw;border-style: ridge"
  >
    <div class="col" style="background-color: white ">
      <br />
      <h2>Team Name: {{ team.team_name }}</h2>
      <h4>Notes</h4>
      {{team.notes}}

      <br />
      <div style="display: flex">
        <a
          class="btn btn-sm btn-info"
          style="width: 50%"
          href="{% url 'charecters:update_team' team.id%}"
          >Edit Team
        </a>
        <a
          class="btn btn-sm btn-danger"
          style="width: 50%"
          href="{% url 'charecters:delete_team' team.id%}"
          >Delete Team</a
        >
      </div>
    </div>
  </div>
  <br />
  {% endfor %}
</div>
{% endblock %}

esaPythonPortfolio/dndDice/templates/dice.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}D&D Dice Roller {% endblock title %}
 
  {% block content %}
 {% block javascript %}

    <script type='text/javascript'>
      function random(dice, id) {
        var randInt = Math.floor(Math.random() * dice) + 1;
        document.getElementById(id).innerHTML = randInt;
        console.log("randInt =", randInt);
      }
    </script>
    {% endblock javascript %}


  <div class="header" style="
    text-align: center;
    font-family: fantasy;
    font-size: 25vw;
    ">
      D&D  
    </div>
      <div style="text-align: center; display: flex; justify-content: space-evenly;" >
        <div class="grid-item">
            <button type="button" class="btn btn-info" onclick="random(20, 'd20')">d20</Button>
            <div style="color:white" id='d20' ></div>
        </div>
        <div class="grid-item">
            <button type="button" class="btn btn-info" onclick="random(12, 'd12')">d12</button>
            <div style="color:white" id='d12' ></div>
        </div>
        <div class="grid-item">
            <button type="button" class="btn btn-info" onclick="random(10, 'd10')"">d10</button>
            <div style="color:white" id='d10'></div>
        </div>
        <div class="grid-item">
            <button type="button" class="btn btn-info" onclick="random(8, 'd8')"">d8</button>
            <div style="color:white" id='d8' ></div>
        </div>
        <div class="grid-item">
            <button type="button" class="btn btn-info" onclick="random(6, 'd6')"">d6</button>
            <div style="color:white" id='d6' ></div>
        </div>
        <div class="grid-item">
            <button type="button" class="btn btn-info" onclick="random(4, 'd4')"">d4</button>
            <div style="color:white" id='d4' ></div>
        </div>
      </div>
    </div>
    {% endblock content %}

esaPythonPortfolio/esaPythonPortfolio/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %} {% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
  </head>
  <body style="background-color: black; font-family: fantasy;">
    <div class="container-fluid">
      <nav
        class=" navbar navbar-expand-lg navbar-light bg-light"
        style="font-family: fantasy;"
      >
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav active">
            <li class="nav-item">
              <a
                class="nav-link active"
                href="{% url 'charecters:display_charecters' %}"
                >See all Charecters</a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'charecters:display_teams' %}">
                See all Teams
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'charecters:create_team' %}">
                Create a Team
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'charecters:create_charecter' %}"
                >Create a Charecter</a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'dndDice:index' %}"
                >D&D Dice Roller</a
              >
            </li>
          </ul>
        </div>
      </nav>
      <div style="font-family: fantasy;">
        {% block content %} {% endblock content %}
      </div>
    </div>
  </body>
</html>

esaPythonPortfolio/esaPythonPortfolio/templates/home.html
{% extends 'base.html' %} 
{% block title %}Home{% endblock title %}
{% block content %} 
<h1
  style="color: white; text-align:center; margin-top:15%; text-decoration: underline;"
>
  WELCOME TO YOUR D&D DATABASE
</h1>

<h4 style="text-align:center;width:50% ;margin-left:25%">
  Here you can store a list of all your charecters by campaign along with their
  information. In addition, the site includes a digital D&D Dice Roller.
</h4>

{% endblock %}